module.exports = {
  "tonight" : "tha neet",
  "night" : "neet",
  "thanks" : "ta",
  "hello" : ["alreet", "here", "how man"],
  "yo" : "here man",
  "think" : "fink",
  "food" : ['scran', 'munch'],
  "very" : ['propa', 'pua'],
  "retard" : "div",
  "silly" : ["divvy", "dafty"],
  "stupid" : ["div", "dafty"],
  "punch" : "smack",
  "laughing" : "creased",
  "don't" : "dain't",
  "sunderland" : ["scumberland", "mackemville", "scum", "filth"],
  "do" : "dee",
  "doing" : "deeing",
  "the" : "tha",
  "yes" : "aye",
  "yeah" : "aye",
  "tomorrow" : "tha morra",
  "mouth" : "mooth",
  "house" : ["hoose"],
  "home" : "yem",
  "homosexual" : ["mincer", "shirt lifter"],
  "gay" : ["mincer", "shirt lifter"],
  "go" : "gan",
  "bye" : "tra",
  "know" : "kna",
  "didn't" : "divint",
  "didnt" : "divint",
  "taking" : "takin",
  "first" : "forst",
  "pure" : "pua",
  "nice" : ["canny", "areet"],
  "good" : ["mint", "class"],
  "great" : "mint",
  "fantastic" : ["class", "belta", "unreal", "mint"],
  "amazing" : ["purely belta", "mint", "class", "godly", "shearer-esque"],
  "god" : "Sir Bobby",
  "kids" : "bairns",
  "children" : "bairns",
  "kid" : "bairn",
  "child" : "bairn",
  "beautiful" : ["lush", "necta", "waxa"],
  "face" : "peart",
  "weed" : "smerk",
  "going" : "ganning",
  "my" : "me",
  "shit" : "shite",
  "woman" : "lass",
  "man" : ["lad", "gadgie"],
  "nice" : "canny",
  "alright" : 'areet',
  "right" : "reet",
  "mad" : ["radge", "mental", "nacka"],
  "drunk" : ["mortal", "monged", "shit faced", "rat arsed"],
  "you" : "ye",
  "i'm" : "am",
  "was" : "wer",
  'newcastle' : 'toon',
  'over' : 'owa',
  "large" : ["walla", "mass-i"],
  "big" : ["walla", "mass-i"],
  "almost" : "aabut",
  "old" : "aad",
  "awkward": "aakward",
  "all" : "aal",
  "above" : "aboon",
  "before": "afore",
  "again" : "agyen",
  "own" : "ain",
  "ahold" : "ahaad",
  "crazy" : "akka",
  "tobacco" : "baccy",
  "bank" : "a hill",
  "below" : "belaa",
  "blow" : "blaa",
  "beer" : "beor",
  "burst" : "borst",
  "brown" : "broon",
  "call" : "caal",
  "toilet" : "cackhoose",
  "beg" : "cadge",
  "came" : "cam",
  "church" : "chorch",
  "desperate" : "clamming",
  "hungry" : "clamming",
  "crow" : "craa",
  "crowd" : "crood",
  "down" : "doon",
  "drown" : "droon",
  "phone" : "fern",
  "football" : "footie",
  "saturday" : "satada",
  "out" : "oot",
  "four" : "fower",
  "her" : "hor",
  "hurt" : "hort"
}
