module.exports = {
  "tonight" : "tha neet",
  "thanks" : "ta",
  "hello" : ["alreet", "here"],
  "yo" : "here man",
  "think" : "fink",
  "food" : ['scran', 'munch'],
  "very" : ['propa', 'pua'],
  "retard" : "div",
  "silly" : ["divvy"],
  "laughing" : "creased",
  "don't" : "dain't",
  "sunderland" : ["scumberland", "mackemville", "scum", "filth"],
  "do" : "dee",
  "doing" : "deeing",
  "the" : "tha",
  "yes" : "aye",
  "yeah" : "aye",
  "tomorrow" : "tha morra",
  "mouth" : "mooth",
  "house" : ["hoose"],
  "home" : "yem",
  "homosexual" : ["mincer", "shirt lifter"],
  "go" : "gan",
  "bye" : "tra",
  "know" : "kna",
  "didn't" : "divint",
  "taking" : "takin",
  "first" : "forst",
  "pure" : "pua",
  "nice" : ["canny", "areet"],
  "good" : ["mint", "class"],
  "great" : "mint",
  "fantastic" : ["class", "belta", "unreal", "mint"],
  "amazing" : ["purely belta", "mint", "class", "godly", "shearer-esque"],
  "god" : "Sir Bobby",
  "kids" : "bairns",
  "children" : "bairns",
  "kid" : "bairn",
  "child" : "bairn",
  "beautiful" : ["lush", "necta", "waxa"],
  "face" : "peart",
  "weed" : "smerk",
  "going" : "ganning",
  "my" : "me",
  "shit" : "shite",
  "woman" : "lass",
  "man" : "lad",
  "nice" : "canny",
  "alright" : 'areet',
  "right" : "reet",
  "mad" : ["radge", "mental", "nacka"],
  "drunk" : ["mortal", "monged", "shit faced", "rat arsed"],
  "you" : "ye",
  "i'm" : "am",
  "was" : "wer",
  'newcastle' : 'toon',
  'over' : 'owa',
  "large" : ["walla", "mass-i"],
}
